// <auto-generated />
using System;
using MS2Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240716092159_ConfigurationIdentity")]
    partial class ConfigurationIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Admin.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MS2Api.Model.DossierPersonnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BenificierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LieuxDintervention")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BenificierId")
                        .IsUnique();

                    b.ToTable("DossierPersonnel");
                });

            modelBuilder.Entity("MS2Api.Model.ParcoursMigratoire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("AnneeEntree")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<int?>("Duree")
                        .HasColumnType("int");

                    b.Property<int?>("DureeEntree")
                        .HasColumnType("int");

                    b.Property<string>("MotifDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NouvelleArrivante")
                        .HasColumnType("bit");

                    b.Property<string>("VilleEntree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("ParcoursMigratoire");
                });

            modelBuilder.Entity("MS2Api.Model.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnes", (string)null);

                    b.HasDiscriminator<string>("PersonneType").HasValue("Personne");
                });

            modelBuilder.Entity("MS2Api.Model.SituationAdministrative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("ActeDeNaissance")
                        .HasColumnType("bit");

                    b.Property<bool?>("CarteConsulaire")
                        .HasColumnType("bit");

                    b.Property<bool?>("CarteMarocaine")
                        .HasColumnType("bit");

                    b.Property<bool?>("CarteSejourValid")
                        .HasColumnType("bit");

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<bool?>("RecepisseDedemande")
                        .HasColumnType("bit");

                    b.Property<bool?>("StatusDeRefugie")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValidationPassport")
                        .HasColumnType("bit");

                    b.Property<bool?>("Visa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("SituationAdministrative");
                });

            modelBuilder.Entity("MS2Api.Model.SituationFamiliale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Accompagne")
                        .HasColumnType("bit");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<bool?>("EnfantAcharge")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Mineur")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nombre")
                        .HasColumnType("int");

                    b.Property<string>("SituationMatrimoniale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("SituationFamiliale");
                });

            modelBuilder.Entity("MS2Api.Model.SituationPsychologique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Enceinte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Handicap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaladieChronique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaladieMentale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SituationDeDetresse")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("SituationPsychologique");
                });

            modelBuilder.Entity("MS2Api.Model.SituationSocioEconomique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("FormationPersonnel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NiveauEducation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("SituationSocioEconomique");
                });

            modelBuilder.Entity("MS2Api.Model.SituationViolence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DossierPersonnelId")
                        .HasColumnType("int");

                    b.Property<bool?>("Indicateur")
                        .HasColumnType("bit");

                    b.Property<string>("Victim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VictimArretation")
                        .HasColumnType("bit");

                    b.Property<string>("Victimrefoulement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersonnelId")
                        .IsUnique()
                        .HasFilter("[DossierPersonnelId] IS NOT NULL");

                    b.ToTable("SituationViolence");
                });

            modelBuilder.Entity("MS2Api.Model.Benificier", b =>
                {
                    b.HasBaseType("MS2Api.Model.Personne");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaysOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeleUrgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDetection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeUnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Benificier");
                });

            modelBuilder.Entity("MS2Api.Model.Utilisateur", b =>
                {
                    b.HasBaseType("MS2Api.Model.Personne");

                    b.HasDiscriminator().HasValue("Utilisateur");
                });

            modelBuilder.Entity("MS2Api.Model.DossierPersonnel", b =>
                {
                    b.HasOne("MS2Api.Model.Benificier", "Benificier")
                        .WithOne("Dossier")
                        .HasForeignKey("MS2Api.Model.DossierPersonnel", "BenificierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benificier");
                });

            modelBuilder.Entity("MS2Api.Model.ParcoursMigratoire", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("ParcoursMigratoire")
                        .HasForeignKey("MS2Api.Model.ParcoursMigratoire", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.SituationAdministrative", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("Administrative")
                        .HasForeignKey("MS2Api.Model.SituationAdministrative", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.SituationFamiliale", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("Familiale")
                        .HasForeignKey("MS2Api.Model.SituationFamiliale", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.SituationPsychologique", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("Psychologique")
                        .HasForeignKey("MS2Api.Model.SituationPsychologique", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.SituationSocioEconomique", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("SocioEconomique")
                        .HasForeignKey("MS2Api.Model.SituationSocioEconomique", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.SituationViolence", b =>
                {
                    b.HasOne("MS2Api.Model.DossierPersonnel", "Dossier")
                        .WithOne("Violence")
                        .HasForeignKey("MS2Api.Model.SituationViolence", "DossierPersonnelId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("MS2Api.Model.DossierPersonnel", b =>
                {
                    b.Navigation("Administrative");

                    b.Navigation("Familiale");

                    b.Navigation("ParcoursMigratoire");

                    b.Navigation("Psychologique");

                    b.Navigation("SocioEconomique");

                    b.Navigation("Violence");
                });

            modelBuilder.Entity("MS2Api.Model.Benificier", b =>
                {
                    b.Navigation("Dossier");
                });
#pragma warning restore 612, 618
        }
    }
}
